### ISSUE TITLE
Cable isn't plugged in (but i can print test page using gui)

### ISSUE THREAD

**Issue by csulit** [shantanubhadoria/python-printer-escpos#2]
Traceback (most recent call last):
  File "printer.py", line 7, in <module>
    outputEndPoint=0x01) # Create the printer object with the connection params
  File "/usr/local/lib/python2.7/dist-packages/escpos/connections.py", line 87, in __init__
    self.__open()
  File "/usr/local/lib/python2.7/dist-packages/escpos/connections.py", line 104, in __open
    raise RuntimeError("Cable isn't plugged in")
RuntimeError: Cable isn't plugged in

**Comment by aaarab** [comment]
just install zadig driver on windows. and it wiil work
